modLoader = "javafml"
loaderVersion = "[43,)"
issueTrackerURL = "https://github.com/EpicSquid/ThermalEndergy/issues"
license = "MIT"
[[mods]]
modId = "thermalendergy"
version = "${file.jarVersion}"
displayName = "Thermal Endergy"
displayURL = "https://minecraft.curseforge.com/projects/thermal-endergy"
credits = "KingLemming and co for great support!"
authors = "EpicSquid"
description = '''
Adding more of the balanced content you love to thermal
'''
[[dependencies.thermalendergy]]
modId = "forge"
mandatory = true
versionRange = "[43.2,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.thermalendergy]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.thermalendergy]]
modId = "thermal"
mandatory = false
versionRange = "[10.0,)"
ordering = "NONE"
side = "BOTH"